set dotenv-load

SOURCES := "./Assoc.aui,./Assoc.aum ./Example.aum"

STDLIB := env_var('AUSTRAL_STD')
STANDARD_SOURCES := STDLIB + '/Buffer.aui' + ',' + STDLIB + '/Buffer.aum'

run: build
  ./bin/assoc

debug: build
  gdb ./bin/assoc

build:
  mkdir -p bin
  austral compile --entrypoint=Example:main --output=bin/assoc {{STANDARD_SOURCES}} {{SOURCES}}
